//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ktbst2210900075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BstKhoa
    {
        public string BstMaKH { get; set; }
        public string BstTenKH { get; set; }
        public Nullable<bool> BstTrangThai { get; set; }
    }
}
