//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ktbst2210900075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BstSinhVien
    {
        public string BstMaSV { get; set; }
        public string BstHoSV { get; set; }
        public string BstTenSV { get; set; }
        public Nullable<System.DateTime> BstNgaySinh { get; set; }
        public Nullable<bool> BstPhai { get; set; }
        public string BstPhone { get; set; }
        public string BstEmail { get; set; }
        public string BstMaKH { get; set; }
    }
}
